openapi: 3.1.0
info:
  title: Pong API
  description: It is an openAPI spec for Pong game
  version: 1.0.0
servers:
  - url: 'http://localhost:8080/v1'
    description:
paths:
  /:
    get:
      summary: Root endpoint
      responses:
        '200':
          description: Welcome message
  /register:
    post:
      summary: Register user
      responses:
        '201':
          description: User registered successfully
  /login:
    post:
      summary: User login
      responses:
        '200':
          description: User logged in successfully
  /logout:
    post:
      summary: User logout
      responses:
        '200':
          description: User logged out successfully
  /leaderboard:
    get:
      summary: Get leaderboard
      responses:
        '200':
          description: List of leaderboard entries
  /start-game:
    post:
      summary: Start a new game
      responses:
        '200':
          description: Game started successfully
  /lobby:
    get:
      summary: Get game lobby
      responses:
        '200':
          description: Current lobby state
  /user/upload-profile-picture:
    post:
      summary: Upload user profile picture
      responses:
        '200':
          description: Profile picture uploaded successfully
  /user/edit-name:
    put:
      summary: Edit user name
      responses:
        '200':
          description: User name updated successfully
  /user/edit-password:
    put:
      summary: Edit user password
      responses:
        '200':
          description: User password updated successfully
  /game/up:
    post:
      summary: Paddle move up
      responses:
        '200':
          description: Paddle moved up
  /game/down:
    post:
      summary: Paddle move down
      responses:
        '200':
          description: Paddle moved down
  /game/ball-speed:
    post:
      summary: Set ball speed
      responses:
        '200':
          description: Ball speed updated
  /quit:
    post:
      summary: Quit game
      responses:
        '200':
          description: Game quit successfully