spring.application.name=pong

# create database tables automatically on application start
spring.jpa.hibernate.ddl-auto=update

spring.jpa.properties.hibernate.format_sql=true

#spring.datasource.url=jdbc:mysql://localhost:3306/pong
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://dmg.th-luebeck.de:3306/MIB5_GruppeI

# never store credentials in configuration files when application is in productive use!
# here: dev mode only!
spring.datasource.username=pong
spring.datasource.password=pong
spring.datasource.username=MIB5_GruppeI
spring.datasource.password=LnAFrJb7FceB

#disable Spring Security auto-configuration
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

#used in JwtTokenService
jwt.secret=myLongSigningSecretOfAtLeast32Base64Characters
jwt.expirationSeconds=3600

#set upload limits
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=10MB
# optional: set update directory
app.upload-dir=uploads
